# 7. 오류 처리

## 오류 코드보다 예외를 사용하라

- 오류가 발생하면 예외를 던져, 호출자 코드를 깔끔하게 할 수 있음
- 각 개념들을 독립적으로 살펴볼 수 있음
- 예전에는 예외를 지원하지 않는 언어가 많았나 봄

## Try-Catch-Finally 문부터 작성하라

- 예외가 발생할 코드를 짤 때는 try-catch-finally 문으로 시작하는 편이 낫다

> 테스트 코드 작성 시, 먼저 강제로 예외를 일으키는 테스트 케이스를 작성한 후 테스트를 통과하게 코드를 작성하는 방법을 권장함
> 
> 
> 자연스럽게 try 블록부터 구현하게 되므로 범위 내에서 본질을 유지하기 쉬워짐
> 

## 미확인(unchecked) 예외를 사용하라

- 확인된 예외는 OCP (Open Closed Principle)을 위반함
    - 하위 단계에서 코드를 변경하면 상위 단계 메서드 선언부를 전부 고쳐야 함
    - 메서드에서 확인된 예외를 던졌는데 catch 블록이 3 단계 위에 있다면 그 사이 메서드 모두가 선언부에 해당 예외를 정의해야 함
    - 최하위 함수에서 새로운 오류를 던질 때, 이 함수를 호출하는 함수가 모두
        
        1) catch 블록에 새로운 예외를 처리하거나
        
        2) 선언부에 throw 절을 추가해야 함
        
    - 상위에 함수가 하위의 함수에서 던지는 예외를 알아야 하므로 캡슐화가 깨짐
- 때로는 확인된 예외도 유용함
    - 아주 중요한 라이브러리를 작성한다면 모든 예외를 잡아야 함

## 예외에 의미를 제공하라

- 오류 메시지에 정보를 담아 예외와 함께 보내기
    - 정보 : 실패한 연산 이름과 실패 유형
    - 애플리케이션이 로깅 기능을 사용한다면 catch 블록에서 오류를 기록하도록 충분한 정보를 보내기
- Java는 모든 예외에 호출 스택을 제공하지만, 실패한 코드의 의도를 파악하기 부족함

## 호출자를 고려해 예외 클래스를 정의하라

- 오류를 정의할 때 프로그래머에게 가장 중요한 관심사는 “오류를 잡아내는 방법”

```tsx
class EmptyStringError extends Error {}
class InvalidNameError extends Error {}
class TooLongNameError extends Error {}

class Person {
    name: string;
    constructor(name: string) {
        this.name = name;
    }
    run() {
        // ...
    }
}

const tom = new Person('tom');

try {
    tom.run();
} catch (error: unknown) {
    if (error instanceof EmptyStringError) {
        reportError(error);
        console.error(error);
    } else if (error instanceof InvalidNameError) {
        reportError(error);
        console.error(error);
    } else if (error instanceof TooLongNameError) {
        reportError(error);
        console.error(error);
    }
} finally {
		// ...
}
```

```tsx
class EmptyStringError extends Error {}
class InvalidNameError extends Error {}
class TooLongNameError extends Error {}
class WrongNameError extends Error {}

class Person {
    name: string;
    constructor(name: string) {
        this.name = name;
    }
    run() {
				if (this.name === '') {
						throw new EmptyStringError('empty~');
				}
        // ...
    }
}

class Human {
    person: Person;
    constructor(name: string) {
        this.person = new Person(name);
    }
    run() {
        try {
            this.person.run();
        } catch (error: unknown) {
            if (error instanceof EmptyStringError) {
                throw new WrongNameError(error.message);
            } else if (error instanceof InvalidNameError) {
                throw new WrongNameError(error.message);
            } else if (error instanceof TooLongNameError) {
                throw new WrongNameError(error.message);
            }
        }
    }
}

const tom = new Human('tom');

try {
    tom.run();
} catch (error: unknown) {
    if (error instanceof WrongNameError) {
        reportError(error);
        console.error(error);
    }
} finally {
    // ...
}
```

- 감싸기 기법은 외부 API 사용할 때 쓸 수 있음 → 의존성을 크게 줄일 수 있음

## 정상 흐름을 정의하라

- 감싸기 기법으로 독자적인 예외를 던지고, 로직을 중단하고 오류 처리하는 것이 적합하지 않은 때도 있음
- 특수 사례 패턴 (Special Case Pattern) : 클래스를 만들거나 객체를 조작해 특수 사례를 처리하는 방식
    - 예외 처리로 특수 상황 처리하지 않음
    - 클래스나 객체가 예외적인 상황을 캡슐화해서 처리함

## null을 반환하지 마라

- `if (xx != null)` 매번 null 체크를 해야함 (일거리가 늘어남) → NullPointerException
- null을 반환하고 싶다면 예외를 던지거나 특수 사례 객체를 반환하기

```tsx
const getEmployees = (list?: string[]) => {
    return list? list : null;
}

const employees = getEmployees();
// employees.length; // Uncaught TypeError: Cannot read properties of null
if (employees !== null) {
    for (let i=0; i < employees.length; i++) {
        console.log(employees[i]);
    }
}
```

```tsx
const getEmployees = (list?: string[]) => {
    if(!list) return [];
    return list;
}

const employees = getEmployees();
for (let i=0; i < employees.length; i++) {
    console.log(employees[i]);
}
```

## null을 전달하지 마라

- 메서드에 인수로 null 전달하지 마라 (정상적인 인수로 null을 기대하는 API 예외)
- 인수로 null이 넘어오면 코드에 문제가 있다는 말

## 결론

- 깨끗한 코드는 읽기도 좋아야 하지만, 안정성도 높아야 함
- 오류 처리를 프로그램 논리와 분리해 독자적인 사안으로 고려하면 튼튼하고 깨끗한 코드를 작성할 수 있음
- 오류 처리를 프로그램 논리와 분리하면 추론이 가능해지며 코드 유지보수성도 크게 높아짐
